### ISSUE TITLE
Hi, nice package! Just what I was looking for.

### ISSUE THREAD

**Issue by bart-heideman** [petercoles/Multilingual-Language-List#1]
One question though.
I am on Laravel 5.7 and couldn't use Languages::lookup(); in my Controller without importing the facade like this on top:
use PeterColes\Languages\LanguagesFacade as Languages;
Am I using it the right way? Does feel like the package discovery isn't working correct?

**Comment by petercoles** [comment]
Autodiscovery namespaces the Languages class to the top level of your application, but your controller will be namespaced to a lower level ```App\Http\Controllers\+```.

So you would need to either invoke Languages with a proceeding backslash
```
\Languages::lookup();
```
or include a ```use``` statement as you have, though you should be OK just doing
```
use Languages;
```

**Comment by bart-heideman** [comment]
Hi Peter,

Thanks for your answer. Your remark about the controller being lower level gave me that extra needed insight to better understand namespacing in general. Thx!
