### ISSUE TITLE
All languages with display language

### ISSUE THREAD

**Issue by Echecivuole** [petercoles/Multilingual-Language-List#7]
How to show all languages with a specific display language?

Languages::lookup([],'it); or other formats not working.

**Comment by Echecivuole** [comment]
solved: Languages::lookup('',$locale);

**Comment by petercoles** [comment]
Actually that won't show all languages, just the minor ones. That is those whose language codes have just two characters. If you genuinely want all languages in the Italian list, then ```Languages::lookup('all', 'it);``` is what you're looking for.
